name: farmacia_white_label
description: "White-label pharmacy app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  mobile_scanner: ^5.2.3
  speech_to_text: ^7.4.0
  url_launcher: ^6.3.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.3.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
